swagger: "2.0"
info:
  title: Learn Chinese Api
  description: APIs for learning chinese
  version: 1
consumes:
  - application/json
produces:
  - application/json
paths:
  /addWord/detailed:
    post:
      summary: Path for adding a new word and all its details
      tags:
      - addWord
      parameters:
      - name: body
        in: body
        description: the data sent from front end
        required: true
        schema:
          type: array
          example: [{
            "id":"3",
            "pingYing":"sān",
            "meaning":"three",
            "character":"三",
            "examples":"三个",
            "notes":""}]
      responses:
        "200":
          description: Success
  /addWord/simple:
    post:
      summary: Path for inputting a word and then fetch meta data via the Line website
      tags:
      - search
      parameters:
      - name: body
        in: body
        description: the data sent from front end
        required: true
        schema:
          type: object
          properties:
            id:
              type: string
            character:
              type: string
            notes:
              type: string
          example: {
            "id":"3",
            "character":"三",
            "notes": ""}
      responses:
        "200":
          description: Success
  /deleteWord/removeFromReview:
    post:
      summary: Path for removing a word from the list of words to review
      tags:
      - removeFromReview
      parameters:
      - name: id
        in: query
        description: remove this ID from the list of words used for review
        required: false
        type: string
        default: "8"
      - name: character
        in: query
        description: the word to remove
        required: false
        type: string
        default: ""
      responses:
        "200":
          description: Success
  /deleteWord/removeWord:
    post:
      summary: Path for removing a word from the database by its index
      tags:
      - removeWord
      parameters:
      - name: id
        in: query
        description: remove this ID from the list of words in the database
        required: true
        type: string
        default: "8"
      responses:
        "200":
          description: Success
  /getWord/id:
    get:
      summary: Path for getting a particular id
      tags:
      - getWord
      parameters:
      - name: id
        in: query
        description: the particular ID to get
        required: false
        type: string
        example: "2"
      responses:
        "200":
          description: Success          
  /getWord/all:
    get:
      summary: Path for getting all the words
      tags:
      - getWord
      responses:
        "200":
          description: Success
  /getWord/lastN:
    get:
      summary: Path for getting the last N words
      tags:
      - last N number of words
      parameters:
      - name: numberToFetch
        in: query
        description: the last number of words to fetch
        required: true
        type: integer
        default: 10
      - name: showPingYing
        in: query
        description: whether to show pingYing in the results
        type: boolean
        default: true
      - name: showCharacter
        in: query
        description: whether to show the simplified Character in the results
        type: boolean
        default: false
      - name: showMeaning
        in: query
        description: whether to show the meaning of the word in the results
        type: boolean
        default: true
      - name: showExample
        in: query
        description: whether to show examples of the word being used in the results
        type: boolean
        default: false
      - name: showNotes
        in: query
        description: whether to show any notes in the results
        type: boolean
        default: true
      responses:
        "200":
          description: Success
  /getWord/randomN:
    get:
      summary: Path for getting a random N words
      tags:
      - random N number of words
      parameters:
      - name: numberToFetch
        in: query
        description: a random number of words to fetch
        required: true
        type: integer
        default: 10
        example: 10
      - name: showPingYing
        in: query
        description: whether to show pingYing in the results
        type: boolean
        default: true
      - name: showCharacter
        in: query
        description: whether to show the simplified Character in the results
        type: boolean
        default: false
      - name: showMeaning
        in: query
        description: whether to show the meaning of the word in the results
        type: boolean
        default: true
      - name: showExample
        in: query
        description: whether to show examples of the word being used in the results
        type: boolean
        default: false
      - name: showNotes
        in: query
        description: whether to show any notes in the results
        type: boolean
        default: true
      responses:
        "200":
          description: Success